### ISSUE TITLE
Cherokee: how to package the old uppercase-only glyphs

### ISSUE THREAD

**Issue by jungshik** [notofonts/cherokee#1]
The current version of Cherokee has only 3/4 height unicameral glyphs. 
An upcoming version will have bicameral (full-height uppercase and a "new" lowercase) glyphs. 
We expect some users to want to access the old glyphs (3/4 height unicameral glyphs). 

There are a couple of ways to make them accessible. 
1. Use 'unic' OT feature to make available the old unicameral glyph. In this case, there'll be only one font per each weight+width+style  
2. Put the old unicameral glyphs in a separate TTF/OTF but package it and the new bicameral font into a TTC/OTC

We might as well generate both packages (TTF/OTF/TTC/OTC). In that case, a question is in which format we want to get the source from Monotype (which way is easier for the pipeline)  
  a. get the source files for notofonts/khmer#10 and post-process to generate notofonts/khmer#11 as well as notofonts/khmer#10. 
  b.  the other way around

/cc @jamesgk , @behdad, @dougfelt

**Comment by simoncozens** [comment]
I think this is closable now that option 1 (`unic` feature) has been implemented.
