### ISSUE TITLE
Cherokee diaeresis below is above

### ISSUE THREAD

**Issue by dscorbett** [notofonts/cherokee#2]
### Font 
NotoSansCherokee-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCherokee-unhinted.zip
Date: 2018-01-14

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+0324 COMBINING DIAERESIS BELOW should go below letters but the font puts it above letters.

### Character data
Ꮜ̤
U+13CC CHEROKEE LETTER SA
U+0324 COMBINING DIAERESIS BELOW

### Screenshot
![Ꮜ̤](https://user-images.githubusercontent.com/1124347/34916751-184472c0-f90b-11e7-932d-3de73be59a02.png)

**Comment by simoncozens** [comment]
<img width="287" alt="Screenshot 2022-06-22 at 13 52 34" src="https://user-images.githubusercontent.com/106728/175033514-ae0e0fda-ca95-43a9-bcda-121704f00df7.png">
"Oops."
